# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f85a56bfd90aa188a146f226dda8a6857d5b98891ef581e26a309d7598fcab61018f53cba399aaab68c16c1086847ef74dbeef187fefb4c5b50477d9d57b7a7e

test:
  secret_key_base: 9f1764ce8f74832da6f1a3563153341c20114d3331d5b3f83a26f3c4ad67c638ba22c99557ab35fa0deee8a87e896b65eeb1082bb8ee8c7826c6a392f1dd4292

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
